spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3305/orderdb?createDatabaseIfNotExist=true&characterEncoding=utf8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
